# Generated by Django 5.1.4 on 2026-10-05 17:08

import apps.hr.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_add_hr_manager_role_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contrato de trabajo')], max_length=20, verbose_name='tipo de documento')),
                ('slug', models.SlugField(max_length=60, verbose_name='serie')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('version', models.PositiveIntegerField(verbose_name='versión')),
                ('file', models.FileField(max_length=255, storage=apps.hr.storage.get_private_storage, upload_to=apps.hr.storage.template_upload_to, verbose_name='archivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='nombre original')),
                ('file_sha256', models.CharField(max_length=64, verbose_name='hash SHA-256')),
                ('detected_variables', models.JSONField(blank=True, default=list, verbose_name='variables detectadas')),
                ('unknown_variables', models.JSONField(blank=True, default=list, verbose_name='variables desconocidas')),
                ('missing_required_variables', models.JSONField(blank=True, default=list, verbose_name='variables obligatorias no usadas')),
                ('is_active', models.BooleanField(default=False, verbose_name='activa')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='activada el')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_templates_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
            ],
            options={
                'verbose_name': 'plantilla de documento',
                'verbose_name_plural': 'plantillas de documento',
                'db_table': 'hr_document_template',
                'ordering': ['document_type', 'slug', '-version'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contrato de trabajo')], max_length=20, verbose_name='tipo de documento')),
                ('template_version', models.PositiveIntegerField(verbose_name='versión de plantilla')),
                ('template_sha256', models.CharField(max_length=64, verbose_name='hash de plantilla')),
                ('subject_name', models.CharField(max_length=255, verbose_name='nombre del trabajador')),
                ('data', models.JSONField(default=dict, verbose_name='datos')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitido'), ('VOIDED', 'Anulado')], default='DRAFT', max_length=10, verbose_name='estado')),
                ('source', models.CharField(choices=[('MANUAL', 'Formulario'), ('ASSISTANT', 'Asistente')], default='MANUAL', max_length=10, verbose_name='origen')),
                ('docx_file', models.FileField(blank=True, max_length=255, storage=apps.hr.storage.get_private_storage, upload_to=apps.hr.storage.document_docx_upload_to, verbose_name='archivo Word')),
                ('pdf_file', models.FileField(blank=True, max_length=255, storage=apps.hr.storage.get_private_storage, upload_to=apps.hr.storage.document_pdf_upload_to, verbose_name='archivo PDF')),
                ('docx_sha256', models.CharField(blank=True, max_length=64, verbose_name='hash del Word')),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='número de documento')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='emitido el')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='anulado el')),
                ('void_reason', models.TextField(blank=True, verbose_name='motivo de anulación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_documents_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_documents_issued', to=settings.AUTH_USER_MODEL, verbose_name='emitido por')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_documents', to='core.personal', verbose_name='trabajador')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='hr.documenttemplate', verbose_name='plantilla')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_documents_voided', to=settings.AUTH_USER_MODEL, verbose_name='anulado por')),
            ],
            options={
                'verbose_name': 'documento generado',
                'verbose_name_plural': 'documentos generados',
                'db_table': 'hr_generated_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Creado'), ('UPDATED', 'Actualizado'), ('ISSUED', 'Emitido'), ('VOIDED', 'Anulado'), ('DOWNLOADED', 'Descargado'), ('PDF_RENDERED', 'PDF generado')], max_length=15, verbose_name='acción')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_document_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hr.generateddocument', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'evento de documento',
                'verbose_name_plural': 'eventos de documento',
                'db_table': 'hr_document_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['document_type', 'is_active'], name='hr_tpl_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(fields=('document_type', 'slug', 'version'), name='hr_template_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type', 'slug'), name='hr_template_one_active_per_series'),
        ),
        migrations.AddConstraint(
            model_name='documenttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='hr_template_version_gte_1'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['document_type', 'status', '-created_at'], name='hr_doc_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['personal'], name='hr_doc_personal_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['created_by'], name='hr_doc_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['subject_name'], name='hr_doc_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='generateddocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ISSUED'), _negated=True), models.Q(('issued_at__isnull', False), ('reference_number__isnull', False)), _connector='OR'), name='hr_doc_issued_has_number_and_date'),
        ),
        migrations.AddConstraint(
            model_name='generateddocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'VOIDED'), _negated=True), models.Q(('void_reason', ''), _negated=True), _connector='OR'), name='hr_doc_voided_has_reason'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['document', 'created_at'], name='hr_event_doc_created_idx'),
        ),
    ]
