# Generated by Django 5.1.4 on 2026-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='pdf_docx_sha256',
            field=models.CharField(blank=True, max_length=64, verbose_name='hash del Word del que se generó el PDF'),
        ),
    ]
