# Generated by Django 5.1.4 on 2026-03-25 05:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('rq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='código de producto')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('unit', models.CharField(max_length=30, verbose_name='unidad')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='categoría')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock mínimo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventario',
                'db_table': 'inventory',
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(blank=True, max_length=50, verbose_name='número de despacho')),
                ('origin', models.CharField(choices=[('CENTRAL', 'Almacén Central'), ('SITE', 'Almacén de Obra'), ('OFFICE', 'Almacén/Bodega de Oficina')], max_length=10, verbose_name='origen')),
                ('dispatch_guide_number', models.CharField(blank=True, max_length=50, verbose_name='número de guía interna')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='entregado el')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches_accepted', to=settings.AUTH_USER_MODEL, verbose_name='aceptado por')),
                ('destination_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_dispatches_received', to='core.department', verbose_name='departamento destino')),
                ('destination_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_dispatches_received', to='core.project', verbose_name='proyecto destino')),
                ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_dispatches', to=settings.AUTH_USER_MODEL, verbose_name='despachado por')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_dispatches', to='rq.request', verbose_name='requerimiento')),
            ],
            options={
                'verbose_name': 'despacho de almacén',
                'verbose_name_plural': 'despachos de almacén',
                'db_table': 'warehouse_dispatches',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispatched', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad despachada')),
                ('quantity_delivered', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='cantidad entregada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehousedispatch', verbose_name='despacho')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_items', to='rq.requestitem', verbose_name='ítem del requerimiento')),
            ],
            options={
                'verbose_name': 'ítem de despacho',
                'verbose_name_plural': 'ítems de despacho',
                'db_table': 'warehouse_dispatch_items',
            },
        ),
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='número de recepción')),
                ('supplier_guide_number', models.CharField(blank=True, max_length=50, verbose_name='número de guía del proveedor')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('conformity_passed', models.BooleanField(blank=True, null=True, verbose_name='conformidad aprobada')),
                ('conformity_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='conformidad verificada el')),
                ('conformity_notes', models.TextField(blank=True, verbose_name='notas de conformidad')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('conformity_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conformity_checks', to=settings.AUTH_USER_MODEL, verbose_name='conformidad verificada por')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_receipts', to='rq.purchaseorder', verbose_name='orden de compra')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_receipts', to=settings.AUTH_USER_MODEL, verbose_name='recibido por')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_receipts', to='rq.request', verbose_name='requerimiento')),
            ],
            options={
                'verbose_name': 'recepción de almacén',
                'verbose_name_plural': 'recepciones de almacén',
                'db_table': 'warehouse_receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='warehousedispatch',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='warehouse.warehousereceipt', verbose_name='recepción origen'),
        ),
        migrations.CreateModel(
            name='WarehouseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad recibida')),
                ('quantity_accepted', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='cantidad aceptada')),
                ('quantity_rejected', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='cantidad rechazada')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='motivo de rechazo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='rq.purchaseorderitem', verbose_name='ítem de OC')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehousereceipt', verbose_name='recepción')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='rq.requestitem', verbose_name='ítem del requerimiento')),
            ],
            options={
                'verbose_name': 'ítem de recepción',
                'verbose_name_plural': 'ítems de recepción',
                'db_table': 'warehouse_receipt_items',
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_type', models.CharField(choices=[('CENTRAL', 'Almacén Central'), ('SITE', 'Almacén de Obra'), ('OFFICE', 'Almacén/Bodega de Oficina')], max_length=10, verbose_name='tipo de almacén')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Para almacén de oficina', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='core.department', verbose_name='departamento')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.inventory', verbose_name='inventario')),
                ('project', models.ForeignKey(blank=True, help_text='Para almacén de obra', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='core.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'stock de inventario',
                'verbose_name_plural': 'stocks de inventario',
                'db_table': 'inventory_stock',
                'unique_together': {('inventory', 'warehouse_type', 'project', 'department')},
            },
        ),
        migrations.AddIndex(
            model_name='warehousereceipt',
            index=models.Index(fields=['request'], name='warehouse_r_request_f749ae_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousereceipt',
            index=models.Index(fields=['purchase_order'], name='warehouse_r_purchas_c2ed66_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousedispatch',
            index=models.Index(fields=['request'], name='warehouse_d_request_2db7cf_idx'),
        ),
    ]
