# Generated by Django 5.1.4 on 2026-04-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_inventory_brand_inventory_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDriveToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='access token')),
                ('refresh_token', models.TextField(verbose_name='refresh token')),
                ('expires_at', models.DateTimeField(verbose_name='token expiry')),
                ('account_name', models.CharField(blank=True, help_text='Email or display name of the connected OneDrive account', max_length=200, verbose_name='cuenta')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OneDrive Token',
                'db_table': 'onedrive_token',
            },
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='document_url',
            field=models.URLField(blank=True, help_text='Link al PDF del vale en OneDrive', max_length=500, verbose_name='URL del documento'),
        ),
    ]
