# Generated by Django 5.1.4 on 2026-04-15 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userrole_user_roles_role_c1a65b_idx_and_more'),
        ('warehouse', '0003_add_onedrive_token_and_document_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=30, unique=True, verbose_name='número de vale')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('TRANSFER', 'Transferencia'), ('ADJUSTMENT', 'Ajuste')], max_length=15, verbose_name='tipo')),
                ('warehouse', models.CharField(choices=[('CENTRAL', 'Almacén Central'), ('SITE', 'Almacén de Obra'), ('OFFICE', 'Almacén/Bodega de Oficina')], max_length=10, verbose_name='almacén')),
                ('source_type', models.CharField(blank=True, choices=[('PURCHASE', 'Compra'), ('RETURN', 'Devolución'), ('TRANSFER_IN', 'Transferencia entrante'), ('INITIAL_LOAD', 'Carga inicial'), ('ADJUSTMENT', 'Ajuste de inventario')], max_length=20, verbose_name='origen')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='proveedor')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='factura')),
                ('destination_type', models.CharField(blank=True, choices=[('PROJECT', 'Proyecto/Obra'), ('DEPARTMENT', 'Departamento'), ('EMPLOYEE', 'Empleado'), ('TRANSFER_OUT', 'Transferencia saliente'), ('ADJUSTMENT', 'Ajuste de inventario')], max_length=20, verbose_name='destino')),
                ('destination_detail', models.CharField(blank=True, max_length=200, verbose_name='detalle destino')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('document_url', models.URLField(blank=True, max_length=500, verbose_name='URL documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_groups', to='core.project', verbose_name='proyecto')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_groups', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'grupo de movimiento',
                'verbose_name_plural': 'grupos de movimiento',
                'db_table': 'movement_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.movementgroup', verbose_name='grupo'),
        ),
    ]
