# Generated by Django 5.1.4 on 2026-08-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userrole_role'),
        ('warehouse', '0005_add_movement_group_fk_to_receipt_dispatch'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorystock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_stock_quantity_gte_0'),
        ),
    ]
