# Generated by Django 5.1.4 on 2026-08-08 02:53

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_add_inventory_stock_quantity_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedrivetoken',
            name='access_token',
            field=apps.core.fields.EncryptedTextField(verbose_name='access token'),
        ),
        migrations.AlterField(
            model_name='onedrivetoken',
            name='refresh_token',
            field=apps.core.fields.EncryptedTextField(verbose_name='refresh token'),
        ),
    ]
