# Generated by Django 5.1.4 on 2026-03-25 05:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('department', models.CharField(blank=True, help_text='Área o departamento del usuario (texto libre, referencia informativa)', max_length=100, verbose_name='área/departamento')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('avatar_url', models.URLField(blank=True, max_length=255, verbose_name='avatar URL')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'users',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: ADM, RRHH, CONT, TI', max_length=20, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, help_text='Usuario con rol Jefe Directo del departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='jefe directo')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='año')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='presupuesto total')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprobado el')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_annual_plans', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por (GG)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_plans', to='core.department', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'plan anual',
                'verbose_name_plural': 'planes anuales',
                'db_table': 'annual_plans',
                'ordering': ['-year', 'department__name'],
                'unique_together': {('year', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Ej: PROY-2026-001', max_length=20, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='ubicación')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='cliente')),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='presupuesto total')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='projects_is_acti_3457d5_idx'), models.Index(fields=['code'], name='projects_code_7205ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='código')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('category', models.CharField(blank=True, help_text='Ej: materiales oficina, equipos TI, mobiliario', max_length=100, verbose_name='categoría')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto presupuestado')),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto comprometido')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto ejecutado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.annualplan', verbose_name='plan anual')),
            ],
            options={
                'verbose_name': 'línea de plan anual',
                'verbose_name_plural': 'líneas de plan anual',
                'db_table': 'annual_plan_lines',
                'unique_together': {('annual_plan', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de partida presupuestal', max_length=50, verbose_name='código partida')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto presupuestado')),
                ('committed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto comprometido en RQs', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto comprometido')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto ejecutado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='core.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'partida presupuestal',
                'verbose_name_plural': 'partidas presupuestales',
                'db_table': 'project_budget_lines',
                'indexes': [models.Index(fields=['project', 'code'], name='project_bud_project_389efa_idx')],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REQUESTER', 'Solicitante'), ('GENERAL_MANAGER', 'Gerente General'), ('CENTRAL_WAREHOUSE', 'Almacén Central'), ('PROJECT_RESIDENT', 'Residente de Proyecto'), ('PROJECT_CONTROL', 'Control de Proyecto'), ('LOGISTICS_COORDINATOR', 'Coordinador Logístico'), ('SITE_WAREHOUSE', 'Almacén de Obra'), ('DIRECT_SUPERVISOR', 'Jefe Directo'), ('ADMIN_MANAGER', 'Gerente Administrativo'), ('LOGISTICS_SUPERVISOR', 'Supervisor Logístico'), ('LOGISTICS_CHIEF', 'Jefe Logístico')], max_length=30, verbose_name='rol')),
                ('flow', models.CharField(blank=True, choices=[('OPERATIONS', 'Operaciones (Proyectos/Obra)'), ('ADMINISTRATIVE', 'Administración (Oficina)')], help_text='A qué flujo pertenece este rol. Null = ambos flujos', max_length=20, null=True, verbose_name='flujo')),
                ('is_primary', models.BooleanField(default=False, help_text='Indica si este es el rol principal del usuario', verbose_name='es rol primario')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='asignado el')),
                ('department_obj', models.ForeignKey(blank=True, help_text='ADM: departamento asignado. Null = acceso global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.department', verbose_name='departamento')),
                ('project', models.ForeignKey(blank=True, help_text='OPS: proyecto asignado. Null = acceso global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.project', verbose_name='proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'rol de usuario',
                'verbose_name_plural': 'roles de usuarios',
                'db_table': 'user_roles',
                'indexes': [models.Index(fields=['user', 'role'], name='user_roles_user_id_aae85d_idx'), models.Index(fields=['role', 'flow'], name='user_roles_role_c1a65b_idx')],
                'unique_together': {('user', 'role', 'project', 'department_obj')},
            },
        ),
    ]
