# Generated by Django 5.1.4 on 2026-03-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='frente',
            field=models.CharField(blank=True, default='OFICINA CENTRAL', help_text='Frente/ubicación. Ej: OFICINA CENTRAL', max_length=200, verbose_name='frente'),
        ),
        migrations.AddField(
            model_name='project',
            name='frente',
            field=models.CharField(blank=True, help_text='Frente/ubicación del proyecto. Ej: MINERA YANACOCHA', max_length=200, verbose_name='frente'),
        ),
    ]
