# Generated by Django 5.1.4 on 2026-04-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_frente_project_frente'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrole',
            name='user_roles_role_c1a65b_idx',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='flow',
        ),
    ]
