# Generated by Django 5.1.4 on 2026-04-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userrole_user_roles_role_c1a65b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='Imagen de firma del usuario (PNG transparente)', upload_to='signatures/', verbose_name='firma'),
        ),
    ]
