# Generated by Django 5.1.4 on 2026-04-15 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_user_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('apellidos_nombres', models.CharField(max_length=255, verbose_name='apellidos y nombres')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='sexo')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('CONVIVIENTE', 'Conviviente')], max_length=15, verbose_name='estado civil')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='celular')),
                ('email_personal', models.EmailField(blank=True, max_length=254, verbose_name='email personal')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=255, verbose_name='nombre contacto emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, verbose_name='telefono contacto emergencia')),
                ('contacto_emergencia_vinculo', models.CharField(blank=True, max_length=50, verbose_name='vinculo contacto emergencia')),
                ('departamento_residencia', models.CharField(blank=True, max_length=100, verbose_name='departamento residencia')),
                ('provincia_residencia', models.CharField(blank=True, max_length=100, verbose_name='provincia residencia')),
                ('distrito_residencia', models.CharField(blank=True, max_length=100, verbose_name='distrito residencia')),
                ('direccion_residencia', models.CharField(blank=True, max_length=300, verbose_name='direccion residencia')),
                ('nivel_educativo', models.CharField(blank=True, choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TECNICO', 'Técnico'), ('UNIVERSITARIO', 'Universitario'), ('POSTGRADO', 'Postgrado')], max_length=20, verbose_name='nivel educativo')),
                ('grado_academico', models.CharField(blank=True, max_length=100, verbose_name='grado academico')),
                ('especialidad_carrera', models.CharField(blank=True, max_length=200, verbose_name='especialidad / carrera')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CESADO', 'Cesado'), ('VACACIONES', 'Vacaciones'), ('LICENCIA', 'Licencia')], default='ACTIVO', max_length=15, verbose_name='estado')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='fecha de ingreso')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='fecha de cese')),
                ('motivo_cese', models.CharField(blank=True, max_length=255, verbose_name='motivo cese')),
                ('sede', models.CharField(blank=True, max_length=100, verbose_name='sede')),
                ('puesto', models.CharField(blank=True, max_length=200, verbose_name='puesto')),
                ('guardia', models.CharField(blank=True, choices=[('A', 'Guardia A'), ('B', 'Guardia B'), ('C', 'Guardia C'), ('D', 'Dia')], max_length=5, verbose_name='guardia')),
                ('condicion_trabajo', models.CharField(blank=True, choices=[('PLANILLA', 'Planilla'), ('RECIBO', 'Recibo por Honorarios'), ('CONTRATO', 'Contrato')], max_length=20, verbose_name='condicion de trabajo')),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='salario')),
                ('sistema_pensiones', models.CharField(blank=True, choices=[('ONP', 'ONP'), ('AFP_HABITAT', 'AFP Habitat'), ('AFP_INTEGRA', 'AFP Integra'), ('AFP_PRIMA', 'AFP Prima'), ('AFP_PROFUTURO', 'AFP Profuturo')], max_length=20, verbose_name='sistema de pensiones')),
                ('entidad_bancaria', models.CharField(blank=True, max_length=100, verbose_name='entidad bancaria')),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, verbose_name='numero de cuenta')),
                ('cci', models.CharField(blank=True, max_length=30, verbose_name='CCI')),
                ('tiene_hijos', models.BooleanField(default=False, verbose_name='tiene hijos')),
                ('hijos_menores_18', models.BooleanField(default=False, verbose_name='hijos menores de 18')),
                ('cantidad_hijos_menores', models.PositiveIntegerField(default=0, verbose_name='cantidad hijos menores')),
                ('nombres_hijos_menores', models.TextField(blank=True, verbose_name='nombres hijos menores')),
                ('asignacion_familiar', models.BooleanField(default=False, verbose_name='asignacion familiar')),
                ('numero_fotocheck', models.CharField(blank=True, max_length=20, verbose_name='N fotocheck')),
                ('talla_zapato', models.CharField(blank=True, max_length=10, verbose_name='talla zapato')),
                ('talla_pantalon', models.CharField(blank=True, max_length=10, verbose_name='talla pantalon')),
                ('talla_camisa', models.CharField(blank=True, max_length=10, verbose_name='talla camisa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='core.project', verbose_name='proyecto')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to=settings.AUTH_USER_MODEL, verbose_name='usuario del sistema')),
            ],
            options={
                'verbose_name': 'personal',
                'verbose_name_plural': 'personal',
                'db_table': 'personal',
                'ordering': ['apellidos_nombres'],
                'indexes': [models.Index(fields=['dni'], name='personal_dni_1b6716_idx'), models.Index(fields=['estado'], name='personal_estado_cdb1ea_idx'), models.Index(fields=['proyecto'], name='personal_proyect_d7bb35_idx')],
            },
        ),
    ]
