# Generated by Django 5.1.4 on 2026-08-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Si está activo, el usuario solo puede cambiar su contraseña hasta que lo haga', verbose_name='debe cambiar contraseña'),
        ),
    ]
