# Generated by Django 5.1.4 on 2026-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Solicitante'), ('GENERAL_MANAGER', 'Gerente General'), ('CENTRAL_WAREHOUSE', 'Almacén Central'), ('PROJECT_RESIDENT', 'Residente de Proyecto'), ('PROJECT_CONTROL', 'Control de Proyecto'), ('LOGISTICS_COORDINATOR', 'Coordinador Logístico'), ('SITE_WAREHOUSE', 'Almacén de Obra'), ('DIRECT_SUPERVISOR', 'Jefe Directo'), ('ADMIN_MANAGER', 'Gerente Administrativo'), ('LOGISTICS_SUPERVISOR', 'Supervisor Logístico'), ('LOGISTICS_CHIEF', 'Jefe Logístico'), ('PASAJES_MANAGER', 'Gestor de Pasajes'), ('HR_MANAGER', 'Gestor de RR. HH.')], max_length=30, verbose_name='rol'),
        ),
    ]
