# Generated by Django 5.1.4 on 2026-04-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rq', '0003_add_quote_cost_approved_status'),
        ('warehouse', '0003_add_onedrive_token_and_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Vinculacion directa al catalogo de inventario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_items', to='warehouse.inventory', verbose_name='Producto de inventario'),
        ),
    ]
