# Generated by Django 5.1.4 on 2026-08-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rq', '0005_notification_dedup_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='role',
            field=models.CharField(choices=[('REQUESTER', 'Solicitante'), ('GENERAL_MANAGER', 'Gerente General'), ('CENTRAL_WAREHOUSE', 'Almacén Central'), ('PROJECT_RESIDENT', 'Residente de Proyecto'), ('PROJECT_CONTROL', 'Control de Proyecto'), ('LOGISTICS_COORDINATOR', 'Coordinador Logístico'), ('SITE_WAREHOUSE', 'Almacén de Obra'), ('DIRECT_SUPERVISOR', 'Jefe Directo'), ('ADMIN_MANAGER', 'Gerente Administrativo'), ('LOGISTICS_SUPERVISOR', 'Supervisor Logístico'), ('LOGISTICS_CHIEF', 'Jefe Logístico'), ('PASAJES_MANAGER', 'Gestor de Pasajes')], max_length=30, verbose_name='rol del ejecutor'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='responsible_role',
            field=models.CharField(choices=[('REQUESTER', 'Solicitante'), ('GENERAL_MANAGER', 'Gerente General'), ('CENTRAL_WAREHOUSE', 'Almacén Central'), ('PROJECT_RESIDENT', 'Residente de Proyecto'), ('PROJECT_CONTROL', 'Control de Proyecto'), ('LOGISTICS_COORDINATOR', 'Coordinador Logístico'), ('SITE_WAREHOUSE', 'Almacén de Obra'), ('DIRECT_SUPERVISOR', 'Jefe Directo'), ('ADMIN_MANAGER', 'Gerente Administrativo'), ('LOGISTICS_SUPERVISOR', 'Supervisor Logístico'), ('LOGISTICS_CHIEF', 'Jefe Logístico'), ('PASAJES_MANAGER', 'Gestor de Pasajes')], max_length=30, verbose_name='rol responsable'),
        ),
    ]
