"""Create (and activate) a DEMO contract template generated by code.

The text is deliberately generic and marked as DEMO: it exists so the module
can be exercised end to end before RR. HH. delivers the approved Word. Upload
the real template from the UI (same series => new version) and activate it.
"""

import io

from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.management.base import BaseCommand
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

from apps.hr.enums import HRDocumentType
from apps.hr.models import DocumentTemplate
from apps.hr.services import template_service

DEMO_BANNER = 'MODELO DEMO — SIN VALOR LEGAL — reemplazar por la plantilla aprobada'

# Each paragraph is written as ONE run so Word-style run splitting never
# breaks a {{ variable }}; {%p ... %} lines are docxtpl paragraph-level tags.
# Every clause is prefixed "[EJEMPLO]": none of this text is approved wording.
BODY = [
    ('h', 'CONTRATO DE TRABAJO (MODELO DEMO — SIN VALOR LEGAL)'),
    ('p', 'N.º {{ numero_documento }}'),
    ('p',
     '[EJEMPLO] Conste por el presente documento el contrato de trabajo que celebran, de una parte, '
     '{{ empresa_razon_social }}, con RUC N.º {{ empresa_ruc }}, domiciliada en {{ empresa_domicilio }}, '
     'representada por {{ representante_nombre }}, identificado con documento N.º {{ representante_dni }}, '
     'en calidad de {{ representante_cargo }}, a quien en adelante se denominará EL EMPLEADOR; y de la '
     'otra parte, {{ nombre_trabajador }}, de nacionalidad {{ nacionalidad_trabajador }}, identificado '
     'con documento N.º {{ dni_trabajador }}, con domicilio en {{ domicilio_trabajador }}, a quien en '
     'adelante se denominará EL TRABAJADOR.'),
    ('p', '[EJEMPLO] PRIMERA: EL EMPLEADOR contrata a EL TRABAJADOR para desempeñar el cargo de {{ cargo }}, '
          'en {{ lugar_trabajo }}.'),
    ('p', '[EJEMPLO] SEGUNDA: El presente contrato se celebra {{ tipo_contrato|lower }}. '
          'El plazo se inicia el {{ fecha_inicio_larga }}.'),
    ('p', '{%p if es_plazo_fijo %}'),
    ('p', '[EJEMPLO] Modalidad del contrato a plazo fijo: {{ modalidad_plazo_fijo }}. '
          'Causa objetiva: {{ causa_plazo_fijo }}. El contrato vence el {{ fecha_fin_larga }} '
          '(duración de {{ plazo_meses }} meses).'),
    ('p', '{%p endif %}'),
    ('p', '[EJEMPLO] TERCERA: EL TRABAJADOR percibirá una remuneración {{ frecuencia_pago }} de {{ sueldo }} '
          '({{ sueldo_en_letras }}).'),
    ('p', '[EJEMPLO] CUARTA: La jornada de trabajo es: {{ jornada_laboral }}. El período de prueba es de '
          '{{ meses_periodo_prueba }} meses.'),
    ('p', '[EJEMPLO] QUINTA: Funciones: {{ funciones }}'),
    ('p', 'Suscrito el {{ fecha_suscripcion_larga }}.'),
    ('p', '\n\n______________________________\t\t______________________________'),
    ('p', 'EL EMPLEADOR\t\t\t\t\tEL TRABAJADOR'),
]


def build_demo_docx() -> bytes:
    doc = Document()
    banner = doc.add_paragraph()
    banner.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = banner.add_run(DEMO_BANNER)
    run.bold = True
    for kind, text in BODY:
        paragraph = doc.add_paragraph()
        if kind == 'h':
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            paragraph.add_run(text).bold = True
        else:
            paragraph.add_run(text)
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run(DEMO_BANNER).italic = True
    out = io.BytesIO()
    doc.save(out)
    return out.getvalue()


class Command(BaseCommand):
    help = 'Genera y activa una plantilla DEMO de contrato de trabajo (idempotente).'

    def add_arguments(self, parser):
        parser.add_argument(
            '--force', action='store_true',
            help='Crea una nueva versión demo aunque ya exista una plantilla activa.',
        )

    def handle(self, *args, **options):
        spec_slug = 'contrato-trabajo'
        active = DocumentTemplate.objects.filter(
            document_type=HRDocumentType.CONTRACT, slug=spec_slug, is_active=True
        ).first()
        if active and not options['force']:
            self.stdout.write(self.style.WARNING(
                f'Ya existe una plantilla activa ({active.name} v{active.version}). '
                'Usa --force para crear otra versión demo.'
            ))
            return

        upload = SimpleUploadedFile(
            'contrato_demo.docx', build_demo_docx(),
            content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        )
        template = template_service.create_template(
            user=None, document_type=HRDocumentType.CONTRACT,
            name='Contrato de trabajo (MODELO DEMO — SIN VALOR LEGAL)', slug=spec_slug,
            notes=DEMO_BANNER, uploaded_file=upload,
        )
        template_service.activate_template(template.pk, user=None)
        self.stdout.write(self.style.SUCCESS(
            f'Plantilla demo creada y activada: {template.name} v{template.version}.'
        ))
