# Generated by Django 5.1.4 on 2026-04-15 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_user_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPasajeDevoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajador', models.CharField(choices=[('STAFF', 'Staff'), ('WORKER', 'Worker')], max_length=10, verbose_name='Tipo de Trabajador')),
                ('tramo', models.CharField(max_length=100, verbose_name='Tramo (Ruta)')),
                ('en_dolares', models.BooleanField(default=False, help_text='Si el monto de referencia de la política está en dólares.', verbose_name='Tarifa en Dólares')),
                ('no_devolucion', models.BooleanField(default=False, help_text='Si está marcado, este tramo no tiene devolución.', verbose_name='Sin Devolución')),
                ('monto_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de Devolución (USD)')),
                ('monto_soles', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de Devolución (PEN)')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Política de Devolución de Pasajes',
                'verbose_name_plural': 'Políticas de Devolución de Pasajes',
                'db_table': 'politica_pasaje_devoluciones',
                'ordering': ['tramo'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorPasajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Proveedor de Pasajes',
                'verbose_name_plural': 'Proveedores de Pasajes',
                'db_table': 'proveedor_pasajes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('B', 'Bajada'), ('S', 'Subida'), ('S/B', 'Subida/Bajada')], max_length=10, verbose_name='Tipo')),
                ('fecha_bajada', models.DateField(blank=True, null=True, verbose_name='Fecha Bajada')),
                ('embarque_bajada', models.CharField(blank=True, max_length=100, verbose_name='Embarque Bajada')),
                ('destino_bajada', models.CharField(blank=True, max_length=100, verbose_name='Destino Bajada')),
                ('fecha_subida', models.DateField(blank=True, null=True, verbose_name='Fecha Subida')),
                ('embarque_subida', models.CharField(blank=True, max_length=100, verbose_name='Embarque Subida')),
                ('destino_subida', models.CharField(blank=True, max_length=100, verbose_name='Destino Subida')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('cargo', models.CharField(blank=True, max_length=255, verbose_name='Cargo')),
                ('tipo_trabajador', models.CharField(choices=[('STAFF', 'Staff'), ('WORKER', 'Worker')], max_length=10, verbose_name='Tipo de Trabajador')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC (factura)')),
                ('razon_social', models.CharField(blank=True, max_length=255, verbose_name='Razón Social (factura)')),
                ('factura_ticket', models.CharField(blank=True, max_length=50, verbose_name='N. Factura / Ticket')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle / Ruta')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Factura')),
                ('mes', models.CharField(blank=True, max_length=20, verbose_name='Mes')),
                ('moneda', models.CharField(choices=[('SOLES', 'Soles'), ('DOLARES', 'Dólares')], default='SOLES', max_length=10, verbose_name='Moneda')),
                ('monto_con_igv_soles', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto con IGV (PEN)')),
                ('monto_con_igv_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto con IGV (USD)')),
                ('tipo_cambio', models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Tipo de Cambio')),
                ('devolucion', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Devolución')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Total (PEN)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('numero_operacion', models.CharField(blank=True, max_length=50, verbose_name='N. Operación')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajes_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajes', to='core.project', verbose_name='Centro de Costo')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajes', to='administracion.proveedorpasajes', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pasaje',
                'verbose_name_plural': 'Pasajes',
                'db_table': 'pasajes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['dni'], name='pasajes_dni_2d6698_idx'), models.Index(fields=['estado'], name='pasajes_estado_77ef23_idx'), models.Index(fields=['fecha'], name='pasajes_fecha_451618_idx')],
            },
        ),
    ]
