# Generated by Django 5.1.4 on 2026-04-15 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('core', '0005_add_personal_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasajes_personal', to='core.personal', verbose_name='personal'),
        ),
    ]
