# Generated by Django 5.1.4 on 2026-04-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_add_personal_fk_to_pasaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200, unique=True, verbose_name='Cargo')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'db_table': 'puesto',
                'ordering': ['cargo'],
            },
        ),
    ]
