# Generated by Django 5.1.4 on 2026-08-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_add_puesto_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasaje',
            name='codigo_id_legado',
            field=models.CharField(blank=True, help_text='ID del registro en el sistema legado (SQL Server). Clave natural para reimportar el CSV histórico sin duplicar.', max_length=50, null=True, unique=True, verbose_name='Código ID (legado)'),
        ),
    ]
